CREATE TABLE tb_missoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    dificuldade VARCHAR(255)
);

CREATE TABLE tb_cadastro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    img_url VARCHAR(255),
    idade INT NOT NULL,
    missoes_id BIGINT,
    CONSTRAINT fk_cadastro_missoes FOREIGN KEY (missoes_id) REFERENCES tb_missoes(id)
);
